name: genc_takim
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^0.3.2
  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_svg: ^0.23.0+1
  flutter_svg_provider: ^0.1.11
  http: ^0.13.4

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: RacingSansOne
      fonts:
        - asset: assets/fonts/RacingSansOne-Regular.ttf
